apiVersion: v1
kind: Service
metadata:
  name: gng-backend
  labels:
    app: gng-backend
    component: api
spec:
  type: ClusterIP
  selector:
    app: gng-backend
  ports:
  - name: http
    port: 8000
    targetPort: http
    protocol: TCP
  sessionAffinity: None
